### ISSUE TITLE
Generating a proof-of-verification

### ISSUE THREAD

**Issue by Retamogordo** [Okm165/stone-prover-cairo0-verifier#1]
Hello,

we are trying adapting the stone-prover-cairo0-verifier for generating a proof of the previous cairo-verification thus enabling generating a chain of proofs for further producing recursive STARKs.

After cairo-compiling of the cairo-verifier in proof_mode and running the entire sequence, we managed to generate a proof-of-verification after running the cpu_air_prover on the private and public inputs produced in the previuos step.

The resulting proof-of-verification was then successfully verified by the stone-verifier.
However, the cairo-verifier fails to verify it.
Prior to that, we modified the proof-of-verification file using "jq '{ proof: . }'..." command so it has the format required by the proof-of-verification.
The error message indicates there is a value that falls out of range in one of the builtins.
So far we have only tried the starknet_with_keccak layout for our experiments.

Is there anything we could miss during the overall process?

**Comment by Okm165** [comment]
Hello Yury
I think this is going to help u, I finished it today
Recursive proofs on recursive layout
https://github.com/Okm165/stone-prover-cairo0-verifier/tree/recursive_poc

For your issue i need more details to solve it best thing would be repo
with the proj
Let me know if the think i sent is helpful for u

Cheers :)


pon., 15 sty 2024 o 16:54 Yury Yukhananov ***@***.***>
napisał(a):

**Comment by Retamogordo** [comment]
Hi Bartosz!

I deeply appreciate your immediate answer and it's likely we need to apply the recursive layout instead of the starknet_with_keccak, as we  won't probably need neither ecdsa nor keccak builtins.
As for the repo, we are just doing our first experiments and don't have anything relevant on github.
The original statement was even simpler that the fibonacci program, it was just an empty main function.
On the other hand the proof-of-verification generation requires enormous amounts of time and memory (more than 300Gb of RAM).
However, I could send you the proof-of-verification.json (maybe with the private_input section stripped off, so it is much lighter.
Would it be useful?

**Comment by Okm165** [comment]
Yeah converting to recursive layout reduces memory consumption by a lot i
managed to run everything in my repo with 70G of ram and those are
recursive proofs of fib and cairo0 verifier

Send everything u find appropriate i will try to make some conclusions out
ot this
Also pls describe the context of the files briefly it will help me
