### ISSUE TITLE
Do we have a way to generate proofs for Cairo1 and verify them using Cairo0/Cairo1 verifier?

### ISSUE THREAD

**Issue by alexzhenyu** [Okm165/stone-prover-cairo0-verifier#3]

**Comment by Okm165** [comment]
@alexzhenyu yes we do https://github.com/lambdaclass/cairo-vm/issues/1705
Do u need guidence?

**Comment by alexzhenyu** [comment]
I saw this issue. I would be very grateful if you could provide me with some guidance.

**Comment by Okm165** [comment]
Cool!!! afaik u have 2 options:

Approach-1:
define Cairo1 program -> [cairo1-run](https://github.com/lambdaclass/cairo-vm/tree/main/cairo1-run) -> [stone_prover](https://github.com/starkware-libs/stone-prover) -> [cairo0_verifier](https://github.com/starkware-libs/cairo-lang/tree/master/src/starkware/cairo/cairo_verifier) / [cairo1_verifier](https://github.com/HerodotusDev/integrity)

Approach-2:
define Cairo1 program -> [Cairo1->Cairo0 bootloader](https://github.com/Okm165/cairo1-cairo0bootloader)  -> [stone_prover](https://github.com/starkware-libs/stone-prover) -> [cairo0_verifier](https://github.com/starkware-libs/cairo-lang/tree/master/src/starkware/cairo/cairo_verifier) / [cairo1_verifier](https://github.com/HerodotusDev/integrity)

**Comment by Okm165** [comment]
@alexzhenyu u can try with one of them when u get into any bump feel free to ping me on telegram! https://t.me/bartolomeo_diaz

**Comment by alexzhenyu** [comment]
> @alexzhenyu u can try with one of them when u get into any bump feel free to ping me on telegram! https://t.me/bartolomeo_diaz

Awesome! You did a great job！
